package com.advert.constant

object Constants {
    val dmCities = mapOf<String,String>(
        "Санкт-Петербург" to "spb.",
        "Екатеринбург" to "ekaterinburg.",
        "Уфа" to "ufa.",
        "Краснодар" to "krasnodar.",
        "Тюмень" to "tyumen.",
        "Нижний Новгород" to "nn.",
        "Казань" to "kazan.",

        )
    val dmUrlConstructor = mapOf<String,String>(
        "Снять" to "rent",
        "Купить" to "sale",
        "Вторичка" to "&category=living&offer_type=flat",
        "Новостройка" to "&category=living&offer_type=layout",
        "Комната" to "&category=living&offer_type=room",
        "Дом, дача" to "&category=living&offer_type=house",
        "Таунхаус" to "&category=living&offer_type=townhouse",
        "Коттедж" to "&category=living&offer_type=village",
        "Участок" to "&category=living&offer_type=lot",
        "Гараж" to "&category=garage&offer_type=garage",
        "Бокс" to "&category=garage&offer_type=garage_box",
        "Машиноместо" to "&category=garage&offer_type=parking_place",
        "БезЗалога" to "&has_deposit=0",
        "БезКомиссии" to "&has_commission=0",
        "БезРемонта" to "&renovation=without_repair",
        "Косметический" to "&renovation=standart",
        "Евро" to "&renovation=well_done",
        "Дизайнерский" to "&renovation=design",
        "БезОтделки" to "&layout_renovation=no_renovation",
        "Черновая" to "&layout_renovation=rough_finish",
        "Предчистовая" to "&layout_renovation=pre_finish",
        "Чистовая" to "&layout_renovation=fine_finish",
        "Монолитный" to "&wall_type=monolith",
        "Кирпично-монолитный" to "&wall_type=brick_monolith",
        "Кирпичны" to "&wall_type=brick",
        "Панельный" to "&wall_type=panel",
        "Блочный" to "&wall_type=block",
        "Деревянный" to "&wall_type=wood",
        "НеПервый" to "&floor_not_last=1",
        "НеПоследний" to "&floor_not_first=1",
        "ТолькоПоследний" to "&floor_last=1",
        "Собственник" to "&is_owner=1",
        "Дети" to "&with_children=1",
        "Животные" to "&with_animals=1",
        "Интернет" to "&amenities=internet",
        "Мебель" to "&amenities=living_furniture",
        "МебельНаКухне" to "&amenities=kitchen_furniture",
        "Кондиционер" to "&amenities=conditioner",
        "Посудомойка" to "&amenities=dish_washer",
        "Телевизор" to "&amenities=tv",
        "Холодильник" to "&amenities=refrigerator",
        "Студия" to "&rooms=st",
        "1" to "&rooms=1",
        "2" to "&rooms=2",
        "3" to "&rooms=3",
        "4+" to "&rooms=4",
    )
    val dmFlatConstructorMap = mapOf<Any,Any>(
        "category" to mapOf<String,String>(
            "Вторичка" to "&category=living&offer_type=flat&",
            "Новостройка" to "&category=living&offer_type=layout&",
            "Комната" to "&category=living&offer_type=room&",
            "Дом, дача" to "&category=living&offer_type=house&",
            "Таунхаус" to "&category=living&offer_type=townhouse&",
            "Коттедж" to "&category=living&offer_type=village&",
            "Участок" to "&category=living&offer_type=lot&",
            "Гараж" to "&category=garage&offer_type=garage&",
            "Бокс" to "&category=garage&offer_type=garage_box&",
            "Машиноместо" to "&category=garage&offer_type=parking_place&",
        ),
        "paymentsRules" to mapOf<String,String>(
            "БезЗалога" to "has_deposit=0",
            "БезКомиссии" to "has_commission=0"
        ),
        "priceType" to mapOf<Boolean,String>(
            true to "&sale_price__",
            false to "&square_price__"
        ),
        "renovation" to mapOf<String,String>(
            "БезРемонта" to "&renovation=without_repair&",
            "Косметический" to "&renovation=standart&",
            "Евро" to "&renovation=well_done&",
            "Дизайнерский" to "&renovation=design&",
        )
    )

    val cianCities = mapOf<String,String>(
        "Санкт-Петербург" to "&region=2",
        "Екатеринбург" to "ekaterinburg.",
        "Уфа" to "ufa.",
        "Краснодар" to "krasnodar.",
        "Тюмень" to "tyumen.",
        "Нижний Новгород" to "nn.",
        "Казань" to "kazan.",

        )
    val cianUrlConstructor = mapOf<String,String>(
        "Снять" to "&deal_type=rent",
        "Посуточно" to "&type=2",
        "Долго" to "&type=-2",
        "Купить" to "&deal_type=sale",
        "Вторичка" to "&offer_type=flat",
        "Дом" to "offer_type=suburban",
        "Комната" to "&offer_type=flat&room0=1",


        "КупитьНовостройка" to "&offer_type=flat&object_type%5B0%5D=2",
        "КупитьВторичка" to "&offer_type=flat&object_type%5B0%5D=1",
        "КупитьДом" to "&offer_type=suburban&object_type%5B0%5D=1",
        "БезЗалога" to "&pledge=0",
        "БезКомиссии" to "&zerocom=0",
        "БезРемонта" to "&repair=1",
        "Косметический" to "&repair=2",
        "Евро" to "&repair=3",
        "Дизайнерский" to "&repair=4",
        "Черновая" to "&has_decoration=1",
        "Предчистовая" to "&has_decoration=1",
        "Чистовая" to "&has_decoration=1",
        "Монолитный" to "&house_material=2",
        "Кирпично-монолитный" to "&house_material=8",
        "Кирпичны" to "&house_material=1",
        "Панельный" to "&house_material=3",
        "Блочный" to "&house_material=4",
        "Деревянный" to "&house_material=5",
        "Сталинка" to "&house_material=6",
        "НеПервый" to "&is_first_floor=0",
        "НеПоследний" to "&floornl=1",
        "ТолькоПоследний" to "&floornl=0",
        "Собственник" to "&offer_seller_type=2",
        "Агент" to "&offer_seller_type=3",
        "Застройщик" to "&offer_seller_type=1",

        "Дети" to "&kids=1",
        "Животные" to "&pets=1",
        "Интернет" to "&internet=1",
        "Мебель" to "&mebel=1",
        "МебельНаКухне" to "&mebel_k=1",
        "Кондиционер" to "&conditioner=1",
        "Посудомойка" to "&dish_washer=1",
        "Телевизор" to "&tv=1",
        "Холодильник" to "&rfgr=1",

        "Студия" to "&room9=1",
        "1" to "&room1=1",
        "2" to "&room2=1",
        "3" to "&room3=1",
        "4+" to "&room4=1",

        "Посуточно" to "&type=2",
        "Надолго" to "&type=4",
        "НесколькоМесяцев" to "&type=3",
        "ОтГода" to "&type=-2",
    )
}

